blog/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
from .feeds import LatestPostsFeed
from .views import search, PostViewSet
from rest_framework import routers 
from django.views.generic import TemplateView


router = routers.DefaultRouter() 
router.register(r'api', PostViewSet) 


app_name = 'blog'
urlpatterns = [
    path('', views.most_viewed, name='most_viewed'),
    path('article/', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^blog/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact_page'),
    url(r'^author/(?P<post_author>[-\w]+)/$',views.post_author, name='post_author'),
    path('search', search, name='search'),
    path('me/', views.me, name='me'),
    path('', include(router.urls)), 
    path('api-auth/', include('rest_framework.urls')),
    path('offline/', views.offline, name='offline'),
    path('fill-dynamic-cache/<int:id>', views.fill_dynamic_cache, name='fill_dynamic_cache'),
    path('must-not-cache', views.must_not_cache, name='must_not_cache'),
    path(
        'sw.js',
        views.ServiceWorkerView.as_view(),
        name=views.ServiceWorkerView.name,
        ),

]

ojas/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path,include
from django.conf.urls import url
from blog.sitemaps import PostSitemap
from django.contrib import admin
from blog import views as blog
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from blog import views 


handler404 = blog.error_404
handler500 = blog.error_500


sitemaps = {
    'static': PostSitemap,
}


urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Contact(models.Model):
    full_name = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(
        upload_to='contact/', blank=True, null=True, default='default/contact.png')
    status = models.CharField(max_length=50,  blank=True, null=True)
    location = models.CharField(max_length=100,  blank=True, null=True)
    bio = models.TextField(max_length=300, blank=True, null=True)
    number = models.PositiveIntegerField(default=919917956610)
    greeting = models.CharField(
        max_length=100,  blank=True, null=True, default='Hi%20Priyanshu')
    email = models.EmailField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True, unique=True)
    twitter = models.URLField(blank=True, null=True, unique=True)
    reddit = models.URLField(blank=True, null=True, unique=True)
    telegram = models.CharField(
        max_length=50, blank=True, null=True, unique=True)
    github = models.URLField(blank=True, null=True, unique=True)
    linkedin = models.URLField(blank=True, null=True, unique=True)

    def __str__(self):
        return self.full_name


class About(models.Model):
    Yes_NO = ((True, 'Yes'), (False, 'No'))

    title = models.CharField(max_length=15, blank=True, null=True)
    description = models.TextField(max_length=100, blank=True, null=True)
    button1_title = models.CharField(max_length=10, blank=True, null=True)
    button1_url = models.URLField(blank=True, null=True, unique=True)
    button2_title = models.CharField(max_length=10, blank=True, null=True)
    button2_url = models.URLField(blank=True, null=True, unique=True)
    email = models.EmailField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True, unique=True)
    twitter = models.URLField(blank=True, null=True, unique=True)
    reddit = models.URLField(blank=True, null=True, unique=True)
    telegram = models.CharField(
        max_length=50, blank=True, null=True, unique=True)
    github = models.URLField(blank=True, null=True, unique=True)
    linkedin = models.URLField(blank=True, null=True, unique=True)
    default_page = models.BooleanField(choices=Yes_NO, default='Yes')

    def __str__(self):
        return self.title


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    full_name = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(
        upload_to='author', blank=True, null=True, default='default/author.png')
    joined = models.DateTimeField(auto_now_add=True)
    bio = models.TextField(max_length=200, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True, unique=True)
    twitter = models.URLField(blank=True, null=True, unique=True)
    reddit = models.URLField(blank=True, null=True, unique=True)
    telegram = models.URLField(blank=True, null=True, unique=True)
    github = models.URLField(blank=True, null=True, unique=True)
    linkedin = models.URLField(blank=True, null=True, unique=True)

    def __str__(self):
        return self.author.username


class Viewer(models.Model):
    post = models.PositiveIntegerField(default=0)
    ip = models.CharField(max_length=16, default=None)
    session = models.CharField(max_length=50, default=None)
    last_visited = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.ip


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    author = models.ForeignKey(
        Author, editable=False, on_delete=models.CASCADE)
    body = RichTextField(max_length=2000, blank=True, null=True)
    image = models.ImageField(
        upload_to='blog/%Y/%m/%d/', blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    video = EmbedVideoField(blank=True, null=True)
    views = models.PositiveIntegerField(editable=False, default=0)
    unique_visitor = models.PositiveIntegerField(editable=False, default=0)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE,)
    name = models.CharField(max_length=80, null=True, blank=True)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    name = forms.CharField(label='Your name', max_length=100, required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Optional',
    }))

    body = forms.CharField(label='Join the discussion', max_length=500, widget=forms.Textarea(attrs={
        'placeholder': '500 characters max',
        'rows': '3',
    }))
    
    class Meta:
        model = Comment
        fields = ('name', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
import time
from django.utils import timezone
from datetime import datetime, timedelta
from django.db.models import Count, Q
from taggit.models import Tag
from .models import Post, Comment, Author, Viewer, Contact, About
from .forms import CommentForm
from rest_framework import viewsets
from .serializers import PostSerializer
import logging
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.templatetags.static import static
from ojas import version

logger = logging.getLogger('ojas.pwa.views')

def offline(request):
    return render(request, 'offline.html')

def fill_dynamic_cache(request, id):
    return render(request, 'fill_dynamic_cache.html', context={'id': id})


@never_cache
def must_not_cache(request):
    return render(request, 'must_not_cache.html', context={'requested_at': timezone.now()})


class ServiceWorkerView(TemplateView):
    template_name = 'sw.js'
    content_type = 'application/javascript'
    name = 'sw.js'

    def get_context_data(self, **kwargs):
        return {
            'version': version,
            'icon_url': static('img/android-icon-512x512.png'),
            'manifest_url': static('manifest.json'),
            'style_url': static('css/tailwind.min.css'),
            'home_url': reverse('blog:most_viewed'),
            'offline_url': reverse('blog:offline'),
        }


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.published.all()
    serializer_class = PostSerializer


def search(request):
    queryset = Post.published.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(body__icontains=query) |
            Q(author__author__username__icontains=query)).distinct()

    return render(request, 'search.html',  {
        'queryset': queryset,
        'query': query
    })


def get_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def error_404(request, exception):
    data = {}
    return render(request, 'error_404.html', data)


def error_500(request):
    data = {}
    return render(request, 'error_500.html', data)


def about_page(request):
    about = About.objects.order_by('pk')[:1]

    if about[0].default_page:
        data = {}
    else:
        data = {'about': about}

    return render(request, 'about.html', data)


def me(request):

    if request.user_agent.is_mobile:
        device = 'mobile'
    if request.user_agent.is_tablet:
        device = 'tablet'
    if request.user_agent.is_pc:
        device = 'pc'

    me = {
        'device': device,
        'bot': request.user_agent.is_bot,
        'touch': request.user_agent.is_touch_capable,
        'browser': request.user_agent.browser.family,
        'browser_version': request.user_agent.browser.version_string,
        'ip': get_ip(request),
        'os': request.user_agent.os.family,
        'time': datetime.now(),
    }

    return render(request, 'me.html', {'me': me})


def contact_page(request):
    contacts = Contact.objects.all()
    return render(request, 'contact.html', {'contacts': contacts})


def most_viewed(request):
    posts = Post.published.order_by('views')[:9]
    return render(request, 'index.html', {'posts': posts})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 9)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'article.html', {'page': page, 'posts': posts, 'tag': tag})


def post_author(request, post_author):
    posts = Post.published.filter(
        author__author__username=post_author).order_by('-publish')
    author = Author.objects.filter(author__username=post_author)

    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'author.html', {'page': page, 'posts': posts, 'author': author})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)

    ip = get_ip(request)
    if not request.session.exists(request.session.session_key):
        request.session.create()
        sess_key = request.session.session_key
        unique_visit = Viewer(post=post.pk, ip=ip, session=sess_key)
        post.views = post.views+1
        post.unique_visitor = post.unique_visitor+1
        unique_visit.save()
        post.save()
    else:
        sess_key = request.session.session_key
        view = Viewer.objects.filter(post=post.pk).filter(
            ip=ip).filter(session=sess_key)
        if not view:
            new_view = Viewer(post=post.pk, ip=ip, session=sess_key)
            new_view.save()
            post.views = post.views+1
            post.unique_visitor = post.unique_visitor+1
            post.save()
        else:
            view = Viewer.objects.filter(last_visited__lte=datetime.now(
                tz=timezone.utc) - timedelta(hours=1))
            if view:
                view[0].last_visited = datetime.now(tz=timezone.utc)
                view[0].save()
                post.views = post.views+1
                post.save()

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.pk)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})

blog/templates/article.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}


<!-- articles -->
<div class="container mt-12 md:mt-20 mx-auto py-4 md:px-12 lg:w-10/12 ">
    <div class="flex flex-wrap justify-center">

        {% for post in posts %}

        <div class="my-1 px-1 w-full md:w-1/2 md:my-2 md:px-2 flex flex-col justify-between lg:my-4 lg:px-4 lg:w-1/3">
          <div class="overflow-hidden bg-gray-50 md:bg-white rounded-lg md:shadow-lg">
         <div class="p-2 md:p-0">
            <a href="{{ post.get_absolute_url }}">
              {% if post.image %}
              <img alt="Placeholder" class="block object-cover h-48 w-full" src="{{post.image.url}}">
              {% else %}
              <img alt="Placeholder" class="block object-cover h-48 w-full" src="{% static 'default/blog.png' %}">
              {% endif %}
            </a>
          </div>
            <div class="md:h-48">
              <div class="overflow-hidden h-32 p-4 mb-3">
                <h1 class="truncate font-bold text-xl mb-2">{{ post.title }}</h1>
                <p class="break-words bg-white text-sm text-black">{{ post.body|markdown|truncatewords_html:20 }}</p>
              </div>
              <div class="mb-5 flex items-center justify-between leading-none mx-3">
                <a   href='{% url "blog:post_author" post.author %}'>
                <div class="flex items-center">
                  <img class="w-10 h-10 rounded-full" src="{{ post.author.image.url }}" alt="autor image">
                  <div class="text-sm ml-2">
                    <p class="text-black leading-none">{{ post.author }}</p>
                    <p class="text-gray-600">{{ post.publish|date:"d M, Y" }}</p>
                  </div>
                </div>
                </a>
                <a href="{{ post.get_absolute_url }}"
                  class="bg-green-500 hover:bg-green-600 text-white rounded-full px-8 py-2">
                  Read More
                </a>
              </div>
            </div>
          </div>
        </div>
    
    
        {% empty %}
        <h2 class="leading-none my-10 text-center">We may need some more articles</h2>
        {% endfor %} 

    </div>

    {% include "pagination.html" with page=posts %}

</div>

{% include 'newsletter.html' %}

{% endblock content %}

blog/templates/common_tags.html
{% for tag in tags %}
<li>
  <a class="text-gray-700 hover:text-gray-900 md:font-semibold pb-2 text-sm"
    href='{% url "blog:post_list_by_tag" tag.slug %}'>{{tag}}</a>
</li>
{% endfor %}

blog/templates/most_commented.html
{% load static %}
{% load custom_tags %}
<div class="container w-full md:mt-4 mx-auto py-4 md:px-12">
  <p class="font-sans font-bold text-3xl mb-5 leading-none text-center text-green-500">Most Discussed</p>
  <div class="max-w-full flex flex-wrap justify-center">

    {% for post in commented_posts %}

    <div class="w-full md:w-1/2 md:my-4 lg:px-4 md:flex mb-8">
      <a href='{{ post.get_absolute_url }}'>
        <div class="md:h-64 h-auto md:w-48 flex-none rounded-t md:rounded-t-none md:rounded-l text-center">
          {% if post.image %}
          <img class="md:border md:border-r-0 md:h-64 h-auto" src="{{ post.image.url }}" alt="uploaded cover image" />
          {% else %}
          <img class="md:border md:border-r-0 md:h-64 h-auto" src="{% static 'default/blog.png'  %}"
            alt="default cover image" />
          {% endif %}
        </div>
      </a>
      <div
        class="overflow-hidden h-48 md:h-64 md:w-full md:border md:border  md:border-l-0 border-grey-light bg-gray-50 md:bg-white rounded-b md:rounded-b-none md:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="overflow-hidden mb-8 h-32 md:h-48">
          <div class="truncate text-black font-bold text-xl mb-2">{{ post.title }}</div>
          <p class="break-words text-grey-800 "> {{ post.body|truncatewords_html:20|markdown }} </p>
        </div>
        <div class="flex items-center justify-between leading-none mx-3">
          <a href='{% url "blog:post_author" post.author %}'>
            <div class="flex items-center">
              <img class="w-10 h-10 rounded-full" src="{{ post.author.image.url }}" alt="autor image">
              <div class="text-sm ml-2">
                <p class="text-black leading-none">{{ post.author }}</p>
                <p class="text-gray-600">{{ post.publish|date:"d M, Y" }}</p>
              </div>
            </div>
          </a>
          <a href="{{ post.get_absolute_url }}"
            class="bg-green-500 hover:bg-green-600 text-white rounded-full px-8 py-2">
            Read More
          </a>
        </div>
      </div>
    </div>
    {% empty %}
    <h2 class="md:text-2xl my-10 text-center">We may need some more articles</h2>
    {% endfor %}
  </div>
</div>

blog/templates/navbar.html
{% load custom_tags %}

<nav id="header" class="fixed w-full z-10 top-0">
<div id="progress" class="h-1 z-20 top-0" style="
        background: linear-gradient(
          to right,
          #10b981 var(--scroll),
          transparent 0
        );
      ">
</div>
<div id="nav-content" class="w-full text-gray-700 bg-gray-50 md:bg-transparent">
  <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    <div class="p-4 flex flex-row items-center justify-between">
      <a href="/" class="text-2xl md:text-3xl font-bold tracking-normal text-gray-900 rounded-lg focus:outline-none focus:shadow-outline">{%  get_title  %}<span style="color: #FF7F50;">.</span></a>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-none" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <div :class="{'flex': open, 'hidden': !open}" class="font-sans flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
      <a class="px-4 py-2 mt-2 text-black md:mt-0 md:ml-4 hover:underline" href="/article">Article</a>
      <a class="px-4 py-2 mt-2 text-black md:mt-0 md:ml-4 hover:underline" href="/about">About</a>
      <a class="px-4 py-2 mt-2 text-black md:mt-0 md:ml-4 hover:underline" href="/contact">Contact</a>
      <div class="relative text-gray-600 bg-white flex items-center rounded-full">
        <form action="{% url 'blog:search' %}" method="get">
        <input name="q" id="search" type="text" placeholder="Search..."  placeholder="Search" class="bg-white h-10 px-4 md:px-6 lg:px-8 rounded-full text-sm placeholder-green-600 focus:outline-none">
        <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
          <svg class="h-4 w-4 fill-current text-green-600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
            <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
          </svg>
        </button>
      </form>
      </div>    
    </div>
  </div>
</div>
</nav>

blog/templates/search.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}
{% block content %}

<p class="font-sans font-bold text-2xl md:text-3xl leading-none mt-24 text-center text-gray-700">
Search results for <span class="text-green-500" >{{ query }}</span></p>


  {% for post in queryset %}

  <div class="mx-auto px-4 py-4 max-w-xl my-auto">
    <div class="bg-gray-50 md:bg-white md:shadow-xl rounded-lg mb-6 ">
      <a href='{{ post.get_absolute_url }}'>
        <div class="p-4 md:flex-shrink-0">
        {% if post.image %}
          <img src="{{post.image.url}}" alt="uploaded cover image"
            class="object-cover h-full w-full rounded-lg rounded-b-none"> 
        {% else %}      
          <img src="{% static 'default/blog.png' %}" alt="default cover image"
            class="object-cover h-full w-full rounded-lg rounded-b-none">        
        {% endif %}
      </div>
      </a>
      <div class="py-1">
        <div class="p-4">
          <h2 class="truncate font-bold mb-2 md:mt-4 text-2xl text-gray-800 tracking-normal">{{ post.title|highlight_search:query }}</h2>
          <p class="break-words text-sm text-gray-700 px-2 mr-1">{{ post.body|markdown|truncatewords_html:30|highlight_search:query }}</p>
        </div>
        <div class="flex items-center justify-between p-2 md:p-4 md:mx-4">
          <a   href='{% url "blog:post_author" post.author %}'>
            <div class="flex items-center">
              <img class="w-12 h-12 object-cover rounded-full" src="{{ post.author.image.url }}" alt="author image">
              <div class="text-sm ml-2">
                <p class="text-black leading-none">{{ post.author.author.username|highlight_search:query }}</p>
                <p class="text-gray-700">{{ post.publish|date:"d M, Y" }}</p>
              </div>
            </div>
          </a>
          <a href="{{ post.get_absolute_url }}"
            class="bg-green-500 hover:bg-green-600 text-white rounded-full px-8 py-2">
            Read More
          </a>
        </div>
      </div>
    </div>
  </div>

  {% empty %}
  <h2 class="leading-none mt-5 h-screen text-gray-800 text-center">No results were found</h2>
  {% endfor %}

{% endblock %}

blog/templates/trending.html
{% load static %}
{% load custom_tags %}
<div class="container w-full md:mt-4 mx-auto py-4 md:px-12">
  <p class="font-sans font-bold text-3xl mb-5 leading-none text-center text-green-500">Trending</p>
  <div class="max-w-full flex flex-wrap justify-center">

    {% for post in trending_posts %}

    <div class="w-full md:w-1/2 md:my-4 lg:px-4 md:flex mb-8">
      <a href='{{ post.get_absolute_url }}'>
        <div class="md:h-64 h-auto md:w-48 flex-none rounded-t md:rounded-t-none md:rounded-l text-center">
          {% if post.image %}
          <img class="md:border md:border-r-0 md:h-64 h-auto" src="{{ post.image.url }}" alt="uploaded cover image" />
          {% else %}
          <img class="md:border md:border-r-0 md:h-64 h-auto" src="{% static 'default/blog.png'  %}"
            alt="default cover image" />
          {% endif %}
        </div>
      </a>
      <div
        class="overflow-hidden h-48 md:h-64 md:w-full md:border md:border  md:border-l-0 border-grey-light bg-gray-50 md:bg-white rounded-b md:rounded-b-none md:rounded-r p-4 flex flex-col justify-between leading-normal">
        <div class="overflow-hidden mb-8 h-32 md:h-48">
          <div class="truncate text-black font-bold text-xl mb-2">{{ post.title }}</div>
          <p class="break-words text-grey-800 "> {{ post.body|truncatewords_html:20|markdown }} </p>
        </div>
        <div class="flex items-center justify-between leading-none mx-3">
          <a href='{% url "blog:post_author" post.author %}'>
            <div class="flex items-center">
              <img class="w-10 h-10 rounded-full" src="{{ post.author.image.url }}" alt="autor image">
              <div class="text-sm ml-2">
                <p class="text-black leading-none">{{ post.author }}</p>
                <p class="text-gray-600">{{ post.publish|date:"d M, Y" }}</p>
              </div>
            </div>
          </a>
          <a href="{{ post.get_absolute_url }}"
            class="bg-green-500 hover:bg-green-600 text-white rounded-full px-8 py-2">
            Read More
          </a>
        </div>
      </div>
    </div>
    {% empty %}
    <h2 class="md:text-2xl my-10 text-center">We may need some more articles</h2>
    {% endfor %}
  </div>
</div>